

### 
GET http://localhost:3000/api/portfolio/view/64de0e8003a8c67bfa6c0232
###
POST  http://localhost:3000/api/portfolio/new


{
  "portfolioData": {
    "userName": "Tanmay Patil",
    "about": "I am a web developer",
    "role": "Full Stack Developer",
    "experiences": [
      {
        "company": "ABC Company",
        "tenure": "2021-2023",
        "designation": "Software Engineer",
        "accomplishments": "Led a team of developers..."
      },
      {
        "company": "XYZ Corporation",
        "tenure": "2019-2021",
        "designation": "Frontend Developer",
        "accomplishments": "Developed user interfaces..."
      }
    ],
    "skills":"python, react, c++",
    "projects": [
      {
        "projectName": "E-commerce Website",
        "projectDesc": "Built a fully functional e-commerce site...",
        "projectImg": "https://cdn.dribbble.com/userupload/7202520/file/original-a2ce657ccba5c143d2faed1b3ff576dc.png?resize=400x0",
        "projectTags": "Web Development, E-commerce"
      },
      {
        "projectName": "Portfolio Website",
        "projectDesc": "Designed and developed a personal portfolio...",
        "projectImg": "https://cdn.dribbble.com/userupload/4060584/file/original-a2dcb88a24da79db509636a26cd98052.png?resize=400x0",
        "projectTags": "Web Design, Personal Branding"
      }
    ],
    "email":"tanmaypatiltp25@gmail.com",
    "linkedinLink":"linkedin.com/mynetwork/",
    "githubLink":"linkedin.com/mynetwork/",
    "instagramLink":"linkedin.com/mynetwork/",
    "userID": "64de0e8003a8c67bfa6c0232"
  }
}
